name: Payment Gateways in Nepal

on:
  pull_request:
    branches: "master"

jobs:
  Markdown Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install mdl
        run: gem install mdl
      - name: Run linter
        run: mdl README.md